Desktop version of the portfolio
ameerhamzakhalid/portfolio-ameer-hamza pull request #5
Opened 2022-03-24 18:26 UTC by ameerhamzakhalid

I added the Desktop version module in index.html.
I added images required for the Desktop version layout according to the template.
I added the CSS properties required for the Desktop version module.

2022-03-24 20:11 UTC, akucintavalent requested changes
Hi there, @ameerhamzakhalid 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### To highlight :tada: :champagne: 
- Nice PR description and title :+1: 
- GitHub flow is followed :+1:


## Required Changes ♻️

- [ ] Please take care of the responsiveness of your application. When you change the size of the window there should not be any possibility to scroll horizontally.

https://user-images.githubusercontent.com/87897753/159994768-62fe345e-6587-4f0b-accd-002118e325e7.mp4

- [ ] Kindly change the font of the titles of your cards to Poppins. Kindly change their size and boldness.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/87897753/159996337-aee471fa-be86-44e7-90fe-a9d951bad3b9.png">

Your design: 
<img width="641" alt="image" src="https://user-images.githubusercontent.com/87897753/159996546-2bc8dae5-0e9e-4325-ae4d-47da92149e92.png">

- [ ] My recent works section title should have only one line

<img width="774" alt="image" src="https://user-images.githubusercontent.com/87897753/159996723-8cf7ad90-2e89-447f-8d55-9af5194bdf00.png">

- [ ] The size 

<img width="409" alt="image" src="https://user-images.githubusercontent.com/87897753/159997229-fd3c0d72-3c68-4c3b-8f35-326790bf8156.png">

- [ ] Kindly fix the distances in your cards:

Your design:
<img width="348" alt="Zrzut ekranu 2022-03-24 o 20 43 26" src="https://user-images.githubusercontent.com/87897753/159997748-6392ad44-a8e1-45c8-bfc0-9585814c6b0e.png">

Figma template:
<img width="356" alt="Zrzut ekranu 2022-03-24 o 20 45 57" src="https://user-images.githubusercontent.com/87897753/159997932-f9e89ba1-1d93-4eaf-9947-863a546a603a.png">

- [ ] There should be a line:

Your design:
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/87897753/159998136-3387668a-3847-4a2c-bfaf-6490af1a07b0.png">

Figma template:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/87897753/159998218-4ea36221-afbf-4c39-908e-54c072b7729a.png">

- [ ] Kindly fix the distances here:

<img width="595" alt="image" src="https://user-images.githubusercontent.com/87897753/159998642-76cb7c8e-0a9d-4d81-a863-427c6e6f3b56.png">


Figma template:
<img width="534" alt="Zrzut ekranu 2022-03-24 o 20 49 47" src="https://user-images.githubusercontent.com/87897753/159999174-ac3571a9-0bc6-45b5-b889-1e7735f2f043.png">

- [ ] These links aren't working. They should lead to the corresponding sections of the page.
<img width="371" alt="image" src="https://user-images.githubusercontent.com/87897753/159999481-1afe72e7-d344-4ce7-a339-4ccffde78639.png">

- [ ] Kindly get rid of this blue line:

<img width="50" alt="image" src="https://user-images.githubusercontent.com/87897753/159999683-09469eb4-0b6f-499a-875c-d6993ca3d80d.png">

- [ ] In your README, kindly give detailed instructions on how to open the page on a local PC. 

- [ ] Please fix the mobile version of your page and remove the possibility to scroll horizontally. Kindly fix the size of the logo. 

<img width="373" alt="image" src="https://user-images.githubusercontent.com/87897753/160001274-543b9825-994f-4f21-b8cd-62fff972073f.png">

- [ ] The empty space after your email should be larger:

Your design:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/87897753/160001543-12f54c1a-bbe9-49a2-ab03-5e18069fe620.png">

Figma template: 
<img width="293" alt="image" src="https://user-images.githubusercontent.com/87897753/160001601-f4ed8ef5-c186-41fc-823f-3e8ce3b2cebe.png">

- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 20:11 UTC, akucintavalent commented on style.css
> +    height: 114px;
- [ ] The color of the border of the input fields should be green(ish) when inputting values:

<img width="434" alt="Zrzut ekranu 2022-03-24 o 21 00 40" src="https://user-images.githubusercontent.com/87897753/160000542-f8298c13-3688-4b29-8853-24718e99081d.png">

2022-03-24 20:11 UTC, akucintavalent commented on index.html
> +              </li>
- [ ] There should be one input for Full name (just like the mobile version) and this should take the space of both First Name and Last Name inputs (shown in the desktop version).

2022-03-25 07:06 UTC, sinansevgi reviewed
Hello @ameerhamzakhalid 👋,

_This is an additional review as a result of the second opinion request._

This project is trying to give you experience in working on loosely defined business requirements to create a proper interface. It can be hard to notice little details in the project, But these little details will be the things that separate you as professional developers from beginners. The requested changes may seem small details but they are really important.

You should be careful **not to break** the mobile version while you are adapting your website to the desktop version. 

As stated in the project specification, following the given design principles (typography, margins, placements) are the part of requirements of this project. Please be sure that you implement the requested changes by the @akucintavalent before going any further on this project.

**From The Project Specification** ⬇️ 
> You must stick to the design as much as possible (e.g., font, colors, images, tests, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

You can always reach me if you have any questions or need further elaboration. 

Keep rocking 🚀!
Sinan Sevgi

2022-03-25 08:34 UTC, ameerhamzakhalid commented
I agree with you. But kindly I need to remind that it's my second week, and
too much early to expect that much performance from me

On Fri, Mar 25, 2022, 12:06 PM Sinan Sevgi ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> Hello @ameerhamzakhalid <https://github.com/ameerhamzakhalid> 👋,
>
> *This is an additional review as a result of the second opinion request.*
>
> This project is trying to give you experience in working on loosely
> defined business requirements to create a proper interface. It can be hard
> to notice little details in the project, But these little details will be
> the things that separate you as professional developers from beginners. The
> requested changes may seem small details but they are really important.
>
> You should be careful *not to break* the mobile version while you are
> adapting your website to the desktop version.
>
> As stated in the project specification, following the given design
> principles (typography, margins, placements) are the part of requirements
> of this project. Please be sure that you implement the requested changes by
> the @akucintavalent <https://github.com/akucintavalent> before going any
> further on this project.
>
> *From The Project Specification* ⬇️
>
> You must stick to the design as much as possible (e.g., font, colors,
> images, tests, margins) using the templates in Figma
> <https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1>
> .
>
> You can always reach me if you have any questions or need further
> elaboration.
>
> Keep rocking 🚀!
> Sinan Sevgi
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ameerhamzakhalid/portfolio-ameer-hamza/pull/5#pullrequestreview-921246473>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASNFZJYCQJ2J5Y2AA7UYX2TVBVQXPANCNFSM5RR6GXYA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2022-03-25 08:55 UTC, sinansevgi commented
> second week, and too much early to expect that much performance from

You have already proven that you can work hard and achieve this by passing the microverse entrance challenges. In order to reach your dreams or goals, you need to push through your limits and past your comfort zone. If you feel that you need more time on a particular topic, you can always choose to repeat the week.

2022-03-25 12:53 UTC, CollinsTatang approved these changes
Hi @ameerhamzakhalid , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-25 14:25 UTC, merged